#!/usr/bin/env bash
# Regenerates docs/architecture/spec-map.md from APP_SPEC.md.
#
# The number, title, line range and "cited by" columns are derived from the files
# themselves, so they cannot drift. The Summary column is hand-written prose and is
# carried over from the existing spec-map.md, keyed by section number — editing
# APP_SPEC.md and re-running this script keeps your summaries.
set -euo pipefail
cd "$(dirname "$0")/.."

python3 - <<'PY'
import re, subprocess
from pathlib import Path

SPEC = Path("APP_SPEC.md")
MAP = Path("docs/architecture/spec-map.md")

lines = SPEC.read_text().split("\n")
total = len(lines)

# --- sections: "## N. Title" -> (num, title, start_line, end_line) 1-indexed
heads = []
for i, line in enumerate(lines):
    m = re.match(r"^## (\d+)\. (.+)$", line)
    if m:
        heads.append((int(m.group(1)), m.group(2).strip(), i + 1))

sections = []
for idx, (num, title, start) in enumerate(heads):
    end = heads[idx + 1][2] - 1 if idx + 1 < len(heads) else total
    sections.append((num, title, start, end))

# --- citations: every "APP_SPEC.md §N" in tracked source
cites = {}
out = subprocess.run(
    ["grep", "-rEn", r"APP_SPEC\.md §[0-9]+",
     "--include=*.kt", "--include=*.kts", "--include=*.sql",
     "app", "core", "feature", "build-logic", "docs"],
    capture_output=True, text=True,
).stdout
for row in out.split("\n"):
    if not row.strip():
        continue
    path = row.split(":", 1)[0]
    for n in re.findall(r"APP_SPEC\.md §(\d+)", row):
        cites.setdefault(int(n), set()).add(Path(path).name)

# --- carry over hand-written summaries from the existing map
summaries = {}
if MAP.exists():
    for row in MAP.read_text().split("\n"):
        m = re.match(r"^\| §(\d+) \|[^|]*\|[^|]*\| ([^|]*)\|", row)
        if m:
            summaries[int(m.group(1))] = m.group(2).strip()

rows = []
for num, title, start, end in sections:
    cited = ", ".join(f"`{c}`" for c in sorted(cites.get(num, []))) or "—"
    rows.append(
        f"| §{num} | {title} | {start}–{end} | {summaries.get(num, '')} | {cited} |"
    )

MAP.parent.mkdir(parents=True, exist_ok=True)
MAP.write_text(f"""# APP_SPEC.md section map

`APP_SPEC.md` is ~750 lines. **Do not read it whole.** Find the section you need below, then read
only its line range:

```bash
sed -n '329,364p' APP_SPEC.md    # §12, Offline-First Strategy
```

The spec's section numbers are **frozen** — {len(cites)} sections are cited by number from KDoc in
the source (see the last column), so renumbering would orphan those references. Add new sections at
the end; never renumber existing ones.

This file is generated by `scripts/gen-spec-map.sh` and verified by `scripts/check-context.sh`.
The Summary column is hand-written and preserved across regenerations; every other column is derived.

| § | Title | Lines | Summary | Cited by |
|---|---|---|---|---|
{chr(10).join(rows)}

Total: {len(sections)} sections, {total} lines.
""")
print(f"wrote {MAP} — {len(sections)} sections, {len(cites)} cited from source")
PY